### PR TITLE
fix : add SIGINT SIGTERM SIGQUIT SIGKILL SIGHUP to software-terms

### PR DESCRIPTION
**Pull request by digger-yu**
# Add/Fix Dictionary

Dictionary: software-terms

## Description

fix : add SIGINT SIGTERM SIGQUIT SIGKILL SIGHUP to software-terms

added it here for now, if there is a more suitable path, I will modify it

## References

https://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html

## Checklist

- [x] By submitting this issue, you agree to follow our
      [Code of Conduct](https://github.com/streetsidesoftware/cspell-dicts/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Jason3S** [comment]
@digger-yu,

Thank you.

These terms already exist in the `cpp` and other dictionaries. But since they are common enough across the industry, it makes sense to add them to `software-terms`.

**Comment by digger-yu** [comment]
@Jason3S 
image

These words are indeed in the cpp related file, my question is why it still says Unknown word

**Comment by Jason3S** [comment]
@digger-yu,

Markdown files do not include the CPP dictionary by default. It is necessary to enable the dictionary.

It is possible to enable the `cpp` dictionary within a Markdown file by adding `<!--- cspell:dictionary cpp --->` to the bottom of the file.

image

**Comment by digger-yu** [comment]
@Jason3S So that's how it is, thanks for the answer.

**Pull request merged**
