### PR TITLE
feat!: Update licenses for several dictionaries to match license of their sources

### PR DESCRIPTION
**Pull request by calvinballing**
# Update licenses for several dictionaries

Dictionaries: en-common-misspellings, fa_IR, he, lt_LT, ro_RO, uk_UA

## Description

Related to #441 

Made the following license changes:

- ~`en-common-misspellings`: `MIT` -> `CC BY-SA 4.0`~
EDIT: Moved to separate branch

- `fa_IR`: `MIT` -> `Apache 2.0`
- `he`: `MIT` -> `AGPLv2`
- `lt_LT`: `MIT` -> `BSD-3-clause`
- `ro_RO`: `LGPL` -> `GPL-3.0`
- `uk_UA`: `LGPL` -> `GPL-3.0`

## References

Dictionary link | cspell documentation of source | Dictionary Source link
-- | -- | --
fa_IR | https://github.com/streetsidesoftware/cspell-dicts/tree/main/dictionaries/fa_IR | https://github.com/b00f/lilak
he | https://github.com/streetsidesoftware/cspell-dicts/tree/main/dictionaries/he |  http://hspell.ivrix.org.il/
lt_LT | https://github.com/streetsidesoftware/cspell-dicts/tree/main/dictionaries/lt_LT | https://github.com/ispell-lt/ispell-lt
ro_RO | https://github.com/streetsidesoftware/cspell-dicts/pull/2113 | https://github.com/ManiacDC/TypingAid/blob/master/Wordlists/Wordlist%20Romanian.txt
uk_UA | https://github.com/streetsidesoftware/cspell-dicts/tree/main/dictionaries/uk_UA | https://github.com/wooorm/dictionaries/tree/master/dictionaries/uk

## Checklist

- [x] By submitting this issue, you agree to follow our
      [Code of Conduct](https://github.com/streetsidesoftware/cspell-dicts/blob/main/CODE_OF_CONDUCT.md)
- [x] Verify that the title starts with the correct prefix:
  - `fix:` - for minor changes like adding words or fixing spelling issues.
  - `feat:` - for a significant change like adding a whole new set of words to a dictionary.
  - `feat!:` - for breaking changes, like file format or licensing changes.
  - `chore:` - for changes that do not impact the content of dictionaries.

### CODE REVIEW

**Comment by Jason3S** [comment]
It is going to take me a bit to read through these.

A few notes:

From [Top 10 Questions About the Apache License | Mend](https://www.mend.io/blog/top-10-apache-license-questions-answered/#:~:text=Is%20the%20Apache%20license%20copyleft):
> **Is the Apache license copyleft?**
No. The Apache 2.0 License is [permissive](https://www.mend.io/blog/top-open-source-licenses-explained/). It allows you to use, modify, and distribute the licensed software, including creating derivative works, without requiring those derivative works to be licensed under the same terms. You can release the modified parts of the code under any license you prefer.
>
>There are some obligations. You must release all the unmodified parts of the software under the same license (the Apache License), and you must include copyright and attribution notices, disclaiming warranties, and provide a copy of the license with any distribution of the software.

**Comment by calvinballing** [comment]
Would it help to separate each of these commits into its own PR?

**Comment by calvinballing** [comment]
> I had gotten stuck on the CC license and hadn't gotten back to it.

Have you reviewed the CC license now, or should I break that commit off into a separate PR so that the rest can be merged and that one can be reviewed later?

**Comment by Jason3S** [comment]
> > I had gotten stuck on the CC license and hadn't gotten back to it.
> 
> Have you reviewed the CC license now, or should I break that commit off into a separate PR so that the rest can be merged and that one can be reviewed later?

If you pull out the CC license, I'll merge this PR. I have been busy and reviewing licenses takes (for me that is) a special kind of attention.

**Comment by calvinballing** [comment]
> > > I had gotten stuck on the CC license and hadn't gotten back to it.
> > 
> > 
> > Have you reviewed the CC license now, or should I break that commit off into a separate PR so that the rest can be merged and that one can be reviewed later?
> 
> If you pull out the CC license, I'll merge this PR. I have been busy and reviewing licenses takes (for me that is) a special kind of attention.

This is done!  The one other change I made is I noticed that for Hebrew dictionary, which is being updated to AGPLv3, while I had correctly used the text of AGPLv3, I had labeled it as AGPLv2 in the other two files for some reason. I fixed these to all consistently reference v3

**Comment by Jason3S** [comment]
> This is done! The one other change I made is I noticed that for Hebrew dictionary, which is being updated to AGPLv3, while I had correctly used the text of AGPLv3, I had labeled it as AGPLv2 in the other two files for some reason. I fixed these to all consistently reference v3

Thank you!

**Pull request merged**
