### PR TITLE
Add some keywords to ruby dict

### PR DESCRIPTION
**Pull request by el-ethan**
I added some ruby/rails keywords that were giving me squigglies. Please let me know if this is the correct way to contribute these, and whether or not this type of contribution is welcome. If so, I will probably be contributing similar things in the future!

image

### CODE REVIEW

**Comment by Jason3S** [comment]
Great! Would you please sort them?

**Comment by Jason3S** [comment]
> I added some ruby/rails keywords that were giving me squigglies. 

That is the best way to improve the dictionary.

> Please let me know if this is the correct way to contribute these, and whether or not this type of contribution is welcome. 

This is exactly what works.

> If so, I will probably be contributing similar things in the future!

That would be wonderful.

**Comment by el-ethan** [comment]
> Would you please sort them?

Whoops! Didn't pick up on the order the first time! Thanks!

**Comment by Jason3S** [comment]
Thank you.

**Pull request merged**
