### PR TITLE
Bulgarian dictionary

### PR DESCRIPTION
**Pull request by rabchev**

### CODE REVIEW

**Comment by Jason3S** [comment]
Thank you.
Please do not include the root `package.json` and `package-lock.json`. For the rest, it is fine.

**Comment by Jason3S** [comment]
I merged it and fixed the `package-lock.json`.  Thank you.

**Comment by rabchev** [comment]
Thank you and sorry I din't have chance to react earlier. Those changes happened by mistake and I was going to revert them but din't have time. Thank you very much again for this very useful extension.

**Comment by Jason3S** [comment]
No problem

**Pull request merged**
