### PR TITLE
fix: add terms variation of Nginx

### PR DESCRIPTION
**Pull request by magnobiet**
# Add/Fix Dictionary

Dictionary: software-terms

## Description

Issue #1784 

## References

- `Nginx` - https://en.wikipedia.org/wiki/Nginx
- `NGINX` - https://www.nginx.com/
- `nginx` - https://hub.docker.com/_/nginx

## Checklist

- [x] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/streetsidesoftware/cspell-dicts/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by magnobiet** [comment]
This is the right way to solve that?

I'm not able to run `npm install` correctly, and because of that, I made the changes manually. It's OK?

**Comment by Jason3S** [comment]
> This is the right way to solve that?
> 
> I'm not able to run `npm install` correctly, and because of that, I made the changes manually. It's OK?

It is ok to edit the word lists online. I don't expect everyone to fork and download the repo.

**Comment by Jason3S** [comment]
Based upon #1784, is this still necessary?

**Comment by magnobiet** [comment]
It is no longer necessary. Thanks.

**Pull request closed without merging**
