### PR TITLE
feat!: Upgrade fa_IR Dictionary

### PR DESCRIPTION
**Pull request by KieranRobson**
# Add/Fix Dictionary

Dictionary: fa_IR

## Description

Upgrade as part of #705

## References

NA

## Checklist

- [x] By submitting this issue, you agree to follow our
      [Code of Conduct](https://github.com/streetsidesoftware/cspell-dicts/blob/main/CODE_OF_CONDUCT.md)
- [x] Verify that the title starts with the correct prefix:
  - `fix:` - for minor changes like adding words or fixing spelling issues.
  - `feat:` - for a significant change like adding a whole new set of words to a dictionary.
  - `feat!:` - for breaking changes, like file format or licensing changes.
  - `chore:` - for changes that do not impact the content of dictionaries.

### CODE REVIEW

**Comment by KieranRobson** [comment]
When running `pmpm run test` , I get tons of unknown word errors, I have tried adding the yaml config with no luck.

**Comment by KieranRobson** [comment]
Pulled the changes and tried to rebuild, same issue.

**Comment by Jason3S** [comment]
@KieranRobson,

I'll take a look.

**Comment by Jason3S** [comment]
I found the issue. The dictionary contains U+200C characters. The tools adds to the words in the dictionary while the spell checker treats them as a word break. I'll fix the tool.

**Comment by Jason3S** [comment]
@KieranRobson,

I do not have permission to fix your fork.

**Comment by KieranRobson** [comment]
@Jason3S How would I go about giving you access?

**Comment by Jason3S** [comment]
It generally asks you to give permissions when you make the pull request.

**Comment by Jason3S** [comment]
Superseded by #2454

**Pull request closed without merging**
