### PR TITLE
fix: Import Standard Python Library

### PR DESCRIPTION
**Pull request by Jason3S**

### CODE REVIEW

**Comment by djmattyg007** [comment]
Is this change supposed to be in a released version of the python dictionary package? I can't find the new wordlist in v3.0.4 of `@cspell/dict-python`

**Comment by Jason3S** [comment]
@djmattyg007,
The dictionary name is `python-common`.

```sh
cspell trace articletranslation
```

image

I think some common terms were missed, see https://github.com/streetsidesoftware/cspell-dicts/pull/1099#issuecomment-1133543621

**Comment by djmattyg007** [comment]
@Jason3S I think you've misunderstood my question. The contents of `python-lib.txt` are not being included in the `@cspell/dict-python` package.

```
❯ yarn add @cspell/dict-python
yarn add v1.22.15
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ @cspell/dict-python@3.0.4
info All dependencies
└─ @cspell/dict-python@3.0.4
Done in 2.03s.

❯ cd node_modules/@cspell/dict-python/

❯ ls -a
.  ..  cspell-ext.json  LICENSE  package.json  python-common.txt.gz  python.txt.gz  README.md

❯ zgrep dataclass python.txt.gz
dataclass_transform
dataclasses

❯ zgrep dataclass python-common.txt.gz

```

**Comment by djmattyg007** [comment]
I might be wrong, it looks like the script you're using just isn't picking up anything in `dataclasses.py` :thinking:

**Comment by Jason3S** [comment]
@djmattyg007,
Thank you. I'll take a look.

**Comment by Jason3S** [comment]
@djmattyg007,

My version of Python was too old and threw an error while parsing `dataclasses.py`.

**Comment by Jason3S** [comment]
@djmattyg007, I just published 3.0.5.

**Pull request merged**
