### PR TITLE
Add more words found in various lorem generators

### PR DESCRIPTION
**Pull request by markgaze**
To create this extended list, I generated 10,000 words with the VS Code `lorem10000` command and 20 paragraphs on both https://loremipsum.io/ and https://www.lipsum.com/ to try and get a better coverage of words 🙂 

Hopefully this will cover more of the words I've encountered and have also been mentioned in: https://github.com/streetsidesoftware/vscode-spell-checker/issues/226

### CODE REVIEW

**Comment by AgentEnder** [comment]
@Jason3S any idea when these words would show up inside the vscode extension? `soluta` still throws a spelling error for me, but I have verified it is in the dict.

**Comment by markgaze** [comment]
> @Jason3S any idea when these words would show up inside the vscode extension? `soluta` still throws a spelling error for me, but I have verified it is in the dict.

Just checked and I have v1.9.4 which includes these 😄

**Comment by Jason3S** [comment]
@AgentEnder 
You have to enable the dictionary, otherwise it is not turned on.
There are a couple of ways:
**In document:**
```
// cspell:locale en, lorem
```
or
```
// cspell:dictionaries lorem-ipsum
```

**VS Code Settings**
Enable dictionary
image

**cspell.json**
```
    "language": "en, lorem",
```
or 
```
    "dictionaries": ["lorem-ipusm"]
```

**Comment by JohnLukeBentley** [comment]
I've apparently enabled lorem ...

image

But most of the lorem is still flagged ...

image

Despite @markgaze's additions.

I used https://marketplace.visualstudio.com/items?itemName=oguzhanyildiz.lorem-text-generator and the "Generate a medium lorem" command.

Perhaps "we" ought include a full Latin dictionary.

**Comment by Jason3S** [comment]
@JohnLukeBentley,

It looks like the extension just calls the api at https://loripsum.net/ to get the words. They do not publish their word list.

**Comment by Jason3S** [comment]
@JohnLukeBentley,

It looks like  https://loripsum.net/ has just used a Latin dictionary of about 7000 words. This is not really [lorem-ipsum (Wikipedia)](https://en.wikipedia.org/wiki/Lorem_ipsum) as the rest of us known it. 

There is a Latin dictionary available for VS Code: [Latin - Code Spell Checker - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-latin)

**Comment by JohnLukeBentley** [comment]
@Jason3S Thanks very much. Installing the Latin dictionary solves it. 

And your point about lorem ipsum being it's own thing is well made ...

https://en.wikipedia.org/wiki/Lorem_ipsum
> Lorem ipsum is typically a corrupted version of [De finibus bonorum et malorum](https://en.wikipedia.org/wiki/De_finibus_bonorum_et_malorum), a 1st-century BC text by the [Roman](https://en.wikipedia.org/wiki/Roman_Republic) statesman and philosopher [Cicero](https://en.wikipedia.org/wiki/Cicero), with words altered, added, and removed to make it nonsensical and improper [Latin](https://en.wikipedia.org/wiki/Latin). The first two words themselves are a [truncation](https://en.wikipedia.org/wiki/Clipping_(morphology)) of dolorem ipsum ("pain itself").

**Pull request merged**
