### PR TITLE
chore: move wxyz terms to its own file.

### PR DESCRIPTION
**Pull request by Jason3S**
# Add/Fix Dictionary

Dictionary: _dart_

## Description

Refactor the dart terms a bit.

## Checklist

- [x] By submitting this pull-request, you agree to follow our [Code of Conduct](https://github.com/streetsidesoftware/cspell-dicts/blob/main/CODE_OF_CONDUCT.md)
- [x] Verify that the title starts with the correct prefix:
  - `fix:` - for minor changes like adding words or fixing spelling issues.
  - `feat:` - for a significant change like adding a whole new set of words to a dictionary.
  - `feat!:` - for breaking changes, like file format or licensing changes.
  - `chore:` - for changes that do not impact the content of dictionaries.

### CODE REVIEW

**Comment by Jason3S** [comment]
@ccoVeille,

PR addresses https://github.com/streetsidesoftware/cspell-dicts/pull/3549#issuecomment-2317755698 by moving the terms into their own file.

@fa0311,

I moved the wxyz terms into their own file to make things clearer why they are there.

**Comment by Jason3S** [comment]
@fa0311,

Do you have a suggestion on a Dart or Flutter repository that should be part of the CSpell integration tests?

CSpell Integration tests run cspell against a list of repositories to make sure the results are consistent.

**Review by ccoVeille — APPROVED** [review]

**Comment by fa0311** [comment]
> Do you have a suggestion on a Dart or Flutter repository that should be part of the CSpell integration tests?

I don't know if this is appropriate for testing, but here are some sample Flutter apps
- https://github.com/flutter/samples
- https://github.com/rrousselGit/riverpod/tree/master/examples


Words that are not used in other languages but occur frequently in Flutter include

- autofocus
- unfocus
- ARGB
- sublist
- unawaited
- cupertino

**Comment by Jason3S** [comment]
@fa0311,

Thank you.

I added `flutter/samples`: https://github.com/streetsidesoftware/cspell/pull/6186

**Pull request merged**
