### PR TITLE
chore: Hoist prepare copying to root

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by nschonni** [comment]
Hmm, this seems to be slowing it down with the mandatory build. Might need to back out some of the changes and just remove the copying to the root

**Comment by Jason3S** [comment]
Where are you seeing a slow down?

**Comment by nschonni** [comment]
> Where are you seeing a slow down?

Sorry, it was with an earlier cut of this before I force pushed over it. I had added a call to `build` which called a slowdown

**Comment by nschonni** [comment]
@Jason3S last commit is just for markdown warnings related to the the publishing creating generated changelogs. Not sure which one of the `pub*` targets should have a call to `lint`, but I think that would fix it in the future.

**Comment by Jason3S** [comment]
> @Jason3S last commit is just for markdown warnings related to the the publishing creating generated changelogs. Not sure which one of the `pub*` targets should have a call to `lint`, but I think that would fix it in the future.

We should just exclude the CHANGELOG.md files. They get automatically modified. Changing them messes with the release cycle.

**Pull request merged**
