### PR TITLE
Add Redis dictionary

### PR DESCRIPTION
**Pull request by GeorchW**
# Add Dictionary

Dictionary: _redis_

## Description

I've added the list of redis commands as a dictionary, since I got squiggly underlines whenever I used them.

## References

I opened [the official docs](https://redis.io/commands/) and used `document.querySelectorAll` on the web console to grab all the commands:

```js
commands = [...document.querySelectorAll("article h1")];
words = commands.flatMap(x => x.innerText.split(/ |\./));
[...new Set(words)].sort().join("\n");
```

This code is not very stable if they restyle their website, and since it took me like 3 minutes to write it, I decided not to commit it.

## Checklist

- [x] By submitting this issue, you agree to follow our
      [Code of Conduct](https://github.com/streetsidesoftware/cspell-dicts/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Jason3S** [comment]
@GeorchW,

What type of files do you use the Redis commands?

**Comment by GeorchW** [comment]
@Jason3S  Varies. It's Python, JS/TS and Markdown for me right now, but there are bindings for pretty much any language

**Comment by GeorchW** [comment]
That was a pretty quick reaction! I see that it's already published on NPM. Can I use the dict in VSCode already?

**Comment by Jason3S** [comment]
@GeorchW,

You can use it in VSCode. You need to follow the installation [instructions](https://www.npmjs.com/package/@cspell/dict-redis#Installation).

You might also need to restart VS Code to pick up the new dictionary.

image

**Pull request merged**
