### PR TITLE
add lib.d.ts words

### PR DESCRIPTION
**Pull request by mad-gooze**
Current typescript dict lacks many words. 
I used this script to extract more words from ts lib.d.ts files (stripping comments)
```js
import { readFile, writeFile } from 'fs/promises';
import glob from 'glob-promise';
import strip from 'strip-comments';
import { splitLine, splitCodeWords } from 'cspell-lib/dist/wordListHelper.js';

const result = new Set();

const minWordLength = 4;

const files = await glob('./node_modules/typescript/lib/**/*.d.ts');
for (const file of files) {
    const content = await readFile(file, 'utf-8');
    strip(content)
        .split('\n')
        .map((line) => {
            splitCodeWords(splitLine(line))
                .filter((word) => word.length >= minWordLength)
                .forEach((word) => result.add(word.toLowerCase()));
        })
}

await writeFile('./typescript.txt', Array.from(result).sort().join('\n'));
```

### CODE REVIEW

**Comment by nschonni** [comment]
interesting idea, but it seems like a lot of these are English words from comments rather than typescript specific keywords and function names

**Comment by mad-gooze** [comment]
> interesting idea, but it seems like a lot of these are English words from comments rather than typescript specific keywords and function names

Nice catch, I'll try to remove comments before tokenizing.

**Comment by mad-gooze** [comment]
done

**Comment by mad-gooze** [comment]
@Jason3S could you please add "hacktoberfest-accepted" label for this pr or "hacktoberfest" repo topic (see #259)?

**Pull request merged**
