### PR TITLE
fix: add "behaviour" and "discolour" to GB English dictionary

### PR DESCRIPTION
**Pull request by liby**
# Add/Fix Dictionary

Dictionary: _dictionaries/en_US/src/additional_words.txt_

## Description

Add "behaviour" and "discolour" to GB English dictionary.

In British English, words ending in "-our" have the letter "u" removed in American English if it is not pronounced. For example: behaviour/behavior, discolour/discolor, labour/labor, etc.

## References

- [Behavior vs. behaviour](https://grammarist.com/spelling/behavior-behaviour/)
- https://www.oxfordlearnersdictionaries.com/definition/english/behaviour
- https://www.oxfordlearnersdictionaries.com/definition/english/discolour?q=discolour

## Checklist

- [x] By submitting this issue, you agree to follow our
      [Code of Conduct](https://github.com/streetsidesoftware/cspell-dicts/blob/main/CODE_OF_CONDUCT.md)
- [x] Verify that the title starts with the correct prefix:
  - `fix:` - for minor changes like adding words or fixing spelling issues.
  - `feat:` - for a significant change like adding a whole new set of words to a dictionary.
  - `feat!:` - for breaking changes, like file format or licensing changes.
  - `chore:` - for changes that do not impact the content of dictionaries.

### CODE REVIEW

**Comment by Jason3S** [comment]
@liby,

Thank you for contributing. These words are already in the dictionary:

`cspell trace behaviour`
image


`cspell trace discolour`
image

**Comment by liby** [comment]
> These words are already in the dictionary

Thank you for the reminder. In a situation like the one shown in the screenshot, how should I troubleshoot the problem?
image

**Comment by Jason3S** [comment]
@liby,

Adding more trouble shooting options to the extension is planned.

## Using Settings

image


## Using the Spell Checker UI

I have included images in case someone else runs into this issue.

1. Open your file:
   image


1. Select `spell`:
   image


1. Select `User` tab:
   Note: your list might be different based upon the installed language extensions.
   image

1. Check English UK: 
   image

1. Save to User.

1. Result: 
   image

**Comment by liby** [comment]
@Jason3S Thank you. You're my hero! Have a nice day.

**Pull request closed without merging**
