### PR TITLE
Add "containername" to software-terms dictionary

### PR DESCRIPTION
**Pull request by Kurt-von-Laven**
This is the name of a recently added argument to mega-linter-runner.

### CODE REVIEW

**Comment by Jason3S** [comment]
@Kurt-von-Laven,

Do you have some examples on where it is used? I suggest `containerName` to be added. In case-insensitive environments, `containername` will also be allowed.

**Comment by Jason3S** [comment]
@Kurt-von-Laven,

I'll add it to the dictionary as `containerName`. It will spell check properly in `.yaml` files.

**Comment by Kurt-von-Laven** [comment]
@Jason3S, totally up to you; I was actually about to close this in favor of megalinter/megalinter#1571.

**Comment by Jason3S** [comment]
@Kurt-von-Laven,

I'm fine with removing it. I searched GitHub for `containername` and found that nearly all of them used `containerName`. Note, the search was unrelated to megalinter.

**Comment by Kurt-von-Laven** [comment]
Sweet; I will wait to remove it until megalinter/megalinter#1571 lands, which will most likely be a few weeks on account of a feature freeze for our v6 release.

**Comment by Kurt-von-Laven** [comment]
The current plan is to land the aforementioned pull request in MegaLinter v7 since it is a breaking change.

**Pull request merged**
