### PR TITLE
fix: add azdo to coding-terms.txt

### PR DESCRIPTION
**Pull request by natescherer**
# Add/Fix Dictionary

Dictionary: software-terms

## Description

This adds the term `azdo`, which is a common abbreviation for Azure DevOps. Thanks!

## References

- https://learn.microsoft.com/en-us/azure/devops/extend/publish/overview?view=azure-devops#prerequisites

## Checklist

- [x] By submitting this pull-request, you agree to follow our [Code of Conduct](https://github.com/streetsidesoftware/cspell-dicts/blob/main/CODE_OF_CONDUCT.md)
- [x] Verify that the title starts with the correct prefix:
  - `fix:` - for minor changes like adding words or fixing spelling issues.
  - `feat:` - for a significant change like adding a whole new set of words to a dictionary.
  - `feat!:` - for breaking changes, like file format or licensing changes.
  - `chore:` - for changes that do not impact the content of dictionaries.

### CODE REVIEW

**Comment by ccoVeille** [comment]
While I'm ok with your change as you are adding it aside other azure words.

I'm a bit worried these are all in "coding terms" dictionary. Azure is not a coding term, it's a cloud hosting provider. I mean it's not a coding term for me.

gcp, azure, aws and co could be in a dedicated dictionary

I'm raising the point because when looking at azure and ass in dictionaries I found python one is filled with such words. While they are not python specific



This point is for @Jason3S 

For me the PR could be merged as is, but you should consider reworking the words.

**Comment by ccoVeille** [comment]
Following my previous comment.

Just found out aws has its own dictionary, so maybe azure, should be in a microsoft one.

We already have Google one.

And about azdo, maybe a better candidate could be software-tools dictionary

**Comment by ccoVeille** [comment]
Don't get me wrong @natescherer your contributions (this one and the other I commented today) are more than welcome.

Here I have an internal monologue about what could be better, and posted it online. 

Being better, doesn't mean you were wrong at first.

Let's wait @Jason3S feedbacks

**Comment by natescherer** [comment]
If y'all think adding an Azure dictionary is worthwhile I'd be happy to compile one. I'm an SRE and I am pretty intimately familiar with the Azure platform as a whole. Just let me know.

**Comment by natescherer** [comment]
Oh, also re: the things you called out in the python dictionary, I know for a fact those are names of Azure Python libraries.

**Comment by ccoVeille** [comment]
> Oh, also re: the things you called out in the python dictionary, I know for a fact those are names of Azure Python libraries.

Oh, good catch

**Comment by ccoVeille** [comment]
Let's wait for @Jason3S point of view

**Comment by ccoVeille** [comment]
> If y'all think adding an Azure dictionary is worthwhile I'd be happy to compile one. I'm an SRE and I am pretty intimately familiar with the Azure platform as a whole. Just let me know.

Great. Let's wait you @Jason3S point of view

**Comment by ccoVeille** [comment]
>  about azdo, maybe a better candidate could be software-tools dictionary

@natescherer what do you think about this?

**Comment by Jason3S** [comment]
@natescherer,

Thank you for the contributions!

It would be wonderful if you could create an Azure dictionary: [How to Create a New Dictionary](https://github.com/streetsidesoftware/cspell-dicts?tab=readme-ov-file#how-to-create-a-new-dictionary). Please let me know if the instructions need to be updated.

Even so, I'll land this PR.

@ccoVeille,

Thank you for the comments and suggestions.

As far as adding it to tools instead, AzDO seems to be very common in code and markdown.

**Pull request merged**
