### PR TITLE
Add "fullmatch" to Python dictionary

### PR DESCRIPTION
**Pull request by Kurt-von-Laven**
This is a function in the `re` module.

### CODE REVIEW

**Comment by Jason3S** [comment]
@Kurt-von-Laven,

There is a script ([here](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/python/scripts/extractLib.py#L7)) that tires to generate all the public method / members of the Python classes. Maybe it should be expanded to include more of the Python source.

Are you interested in adding a few more paths to be scanned?

**Comment by Kurt-von-Laven** [comment]
That does seem preferable to adding words one-by-one. Thanks for the suggestion. I'm a little confused as to what `temp/python/cpython/Lib` contains though. My intuition says [the `Lib` directory of CPython](https://github.com/python/cpython/tree/main/Lib), but I know that contains [`fullmatch`](https://github.com/python/cpython/blob/884eba3c76916889fd6bff3b37b8552bfb4f9566/Lib/re/__init__.py#L166-L169) at least at `HEAD`. Did you have particular paths in mind to add? I feel like I'm missing something here.

**Comment by Jason3S** [comment]
@Kurt-von-Laven,
The script downloads the entire CPython repo and then scans the Lib directory looking for public interfaces. It uses the built-in python parser to scan the files. It skips files that start with `_` since I assumed they were private, but as a result it is also skipping the `__init__.py` files.

I'm not a Python programmer. Do you know convention? Any suggestions on which files should be included?

**Comment by Kurt-von-Laven** [comment]
Ah, I completely missed the filter below; thank you for explaining. You are correct about the convention of files starting with `_` being intended for internal use. My instinct would be to try continuing to exclude those, but include files starting with `__`. Happy to open a pull request if that seems like a reasonable iteration to you.

**Comment by Jason3S** [comment]
@Kurt-von-Laven,

I made some fixes to the script. I hope we have everything now. See #1107, #1108, #1109

**Pull request merged**
