### PR TITLE
Add "don't" to US English dictionary.

### PR DESCRIPTION
**Pull request by Kurt-von-Laven**

### CODE REVIEW

**Comment by Jason3S** [comment]
@Kurt-von-Laven,

Are you seeing an issue with `don't`? It is already part of the English dictionaries.

`cspell trace "don't"`:

image

**Comment by Kurt-von-Laven** [comment]
Oops; that is what I get for assuming alphabetical order. The issue is actually with "Dont" in a variable name. I think this is really a feature request to support ignoring missing apostrophes in contexts where they are invalid?

**Comment by Jason3S** [comment]
Handling `don't` vs `dont` and others like `didn't` vs `didnt` has been difficult.

I do not think they should be added to the English dictionary, since they are not correct.

But, like you pointed out, there are cases where it makes sense to allow them.

My suggestion is to create a new dictionary `english-exceptions-in-code` and include those word there. The dictionary can then be included with programming languages but not included with Markdown or LaTeX.

By having it as a named dictionary, it allows people to exclude it if they do not want it:

```js
"dictionaries": [
  "!english-exceptions-in-code"
]
```

**Comment by Kurt-von-Laven** [comment]
I like the flexibility of being able to exclude the exceptions, but I wonder if there will be words that are valid in some code but not other code. I like how editorconfig lets you specify cascading rules on sets of extensions. Maybe the dictionary you described could be programmatically generated using something similar where the rules are disallowed characters in the language. Then if people wanted their language supported more gracefully by cspell, they could tweak those rules in a few minutes. I suppose this strategy would cause cspell to overlook comments containing "dont," but I agree with the project's philosophy of minimizing false positives.

The simplest thing may be to programmatically generate code versions of dictionaries by stripping the most commonly unsupported characters and words already in the source dictionary though.

**Comment by Jason3S** [comment]
The spell checker already supports extension based and programming language based settings.

```js
"languageSettings": [
    {
        "languageId": ["typescript", "javascript"],
        "dictionaries": ["english-exceptions-in-code"]
    }
],
// And:
"overrides": [
    {
        "filename": ["*.ts"],
        "dictionaries": ["english-exceptions-in-code"]
    }
]
```

**Comment by Jason3S** [comment]
Longer term, I'm hoping to add context based settings that would allow having different settings for strings, comments, etc.

**Comment by Kurt-von-Laven** [comment]
> The spell checker already supports extension based and programming language based settings.

I wasn't aware of the language and filename based settings. Those look awesome but also slightly different than what I was imagining. I believe one would need `typescript-english-exceptions-in-code`, `javascript-english-exceptions-in-code`, etc. dictionaries in order to use those settings in this context, which sounds easy to use but unpleasant to maintain.

> Longer term, I'm hoping to add context based settings that would allow having different settings for strings, comments, etc.

Very neat; that definitely seems like the best long-term solution. In light of that, something simple like stripping commonly disallowed characters in code and removing words already in the source dictionary makes the most sense to me. It doesn't sound fun to manually maintain separate code exception dictionaries for each supported language without a way to keep them in sync with their source dictionaries.

**Comment by Kurt-von-Laven** [comment]
Should this pull request be closed in favor of a new issue?

**Comment by Jason3S** [comment]
Yes, let's close this one.

I think creating a very small dictionary is the way to go. Something like "english-conjugations-for-code", which can be easily included when spell checking code.

**Pull request closed without merging**
