### PR TITLE
chore: Move GZ out of source control

### PR DESCRIPTION
**Pull request by nschonni**
Move to a prepublish step so that TXT changes don't need to be submitted with GZ changes.
This avoids zip diffs being missed when publishing new dics

### CODE REVIEW

**Comment by nschonni** [comment]
Not sure why `packages/fa_IR/fa-IR.trie.gz` is being shown as a text instead of binary file

**Comment by nschonni** [comment]
Seems like the `test-build` target could be removed with this too

**Comment by Jason3S** [comment]
Thank you for the help.
@nschonni, in principle I agree with you.
The decision was made to keep the binaries in the repository because they can take hours to build. 
I'm trying to speed the build process up, but until that is the case, I think it is better to keep the binaries in.

**Comment by nschonni** [comment]
Yeah, I'm seeing the build time issue now 😄 
Wonder if there is another way to check to see if zips need to be rebuilt before publishing? Just noticed that the CPP dictionary needed to be rebuilt to get in the changes, but was trying to see if there was a non-human tracking way of doing that for next time

**Comment by nschonni** [comment]
Actually, I think it is mostly the "trie" dictionaries that take awhile to build, does that sound right?

**Comment by Jason3S** [comment]
Yes, that is right. The tries take some time to build. They convert all the hunspell files into a format that is faster to access and smaller. With some dictionaries, it is millions of words.

**Comment by nschonni** [comment]
I'll see what the CI says now, but I changed this so that it's just the TXT zips that are regenerated on publish/lerna bootstrap. Locally it was 2-4 minutes

**Comment by Jason3S** [comment]
That should work.

**Comment by nschonni** [comment]
Seems ok on CI.
Looks like `custom_scientific_US.dic.txt` is probably one of the slower ones. Should it actually be .dic & trie compiled instead of .dict.txt and regular complied?

**Comment by Jason3S** [comment]
Would you use `prepare` instead of `prepublish`. [Prepublish has been deprecated](https://docs.npmjs.com/misc/scripts#prepublish-and-prepare)

**Comment by Jason3S** [comment]
I left it as a `.txt.gz` since it compressed better that way.
Just exclude that one from the set. It doesn't change very often.

**Comment by nschonni** [comment]
Changed to `prepare`. I'll leave the `custom_scientific_US.dic.txt` in, since it's probably easier to treat all the TXT files the same, and doesn't add a ton of time

**Pull request merged**
