### PR TITLE
fix: Add `untriggered`

### PR DESCRIPTION
**Pull request by Nightblade**
# Add/Fix Dictionary

Dictionary: `shared-additional-words.txt`

## Description

- Add `untriggered`

## References

- [untriggered](https://en.wiktionary.org/wiki/untriggered)

## Checklist

- [x] By submitting this issue, you agree to follow our
      [Code of Conduct](https://github.com/streetsidesoftware/cspell-dicts/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Jason3S** [comment]
@Nightblade,

Thank you for contributing.

I think this is more of a full-stack term. The meaning is incorrect on Wiktionary. It means "It was triggered and is no longer triggered", not `not triggered`. I understand that in web development, it could be an event to mean the triggered state was removed.

I'm reluctant to add any words to ALL English dictionaries that do not appear in Google Ngram. I would rather first introduce it into its respective jargon dictionary. If it becomes popular, then promote it.

**Comment by Nightblade** [comment]
An armed trap can be said to be in an `untriggered` state.

**Comment by Nightblade** [comment]
> The meaning is incorrect on Wiktionary.
I'm sorry, how is it wrong?

**Comment by Jason3S** [comment]
> An armed trap can be said to be in an `untriggered` state.

You are right.

**Comment by Jason3S** [comment]
> > The meaning is incorrect on Wiktionary.
> 
> I'm sorry, how is it wrong?

Wrong is too strong, more that it is too simple. `not` and `un-` are not the same. `un-` implies a sense of movement or time.

For example:
- The crash inspector looked at the untriggered airbags.
- The crash inspector looked at the airbags that _were not_ triggered.

**Pull request closed without merging**
