### PR TITLE
Add scientific-terms-gb, resolves #51

### LINKED ISSUE #51: Missing UK Scientific Dictionary?
I'll keep this brief.

I notice you have this http://jpetrie.net/wp-content/uploads/custom_scientific_US.dic
But do not appear to have the UK version http://jpetrie.net/wp-content/uploads/custom_scientific_UK.dic

Thanks,

tecosaur

### PR DESCRIPTION
**Pull request by calvinballing**
# Add Dictionary

Dictionary: scientific-terms-gb

## Description

Adds custom_scientific_UK dictionary, resolving https://github.com/streetsidesoftware/cspell-dicts/issues/51.

## References

- https://web.archive.org/web/20160702233136/http://jpetrie.net/wp-content/uploads/custom_scientific_UK.dic

## Checklist

- [x] By submitting this issue, you agree to follow our
      [Code of Conduct](https://github.com/streetsidesoftware/cspell-dicts/blob/main/CODE_OF_CONDUCT.md)
- [x] Verify that the title starts with the correct prefix:
  - `fix:` - for minor changes like adding words or fixing spelling issues.
  - `feat:` - for a significant change like adding a whole new set of words to a dictionary.
  - `feat!:` - for breaking changes, like file format or licensing changes.
  - `chore:` - for changes that do not impact the content of dictionaries.

### CODE REVIEW

**Comment by calvinballing** [comment]
Should the package-lock.json file be removed?  I don't see that in the other dictionary directories.

**Comment by calvinballing** [comment]
> Should the package-lock.json file be removed? I don't see that in the other dictionary directories.

I removed package-lock.json

**Comment by Jason3S** [comment]
> > Should the package-lock.json file be removed? I don't see that in the other dictionary directories.
> 
> I removed package-lock.json

Thank you. This repo uses `pnpm` instead of `npm` because it does a better job with workspaces.

**Comment by calvinballing** [comment]
Thanks for the fixes!

**Pull request merged**
