### PR TITLE
Fix package name for polish dictionary

### PR DESCRIPTION
**Pull request by adam-zielonka**

### CODE REVIEW

**Comment by nschonni** [comment]
Makes sense, but maybe the existing package should be depreciated and replaced with this format, that matches the other language dictionaries

**Comment by adam-zielonka** [comment]
For me, both cases are OK, but changing to the standard way make sense for future of this project. Should we consider changing all wrong named packages?
```
packages/en_US/package.json:  "name": "cspell-dict-en_us",
packages/pl_PL/package.json:  "name": "cspell-dict-pl_pl",
packages/ru_RU/package.json:  "name": "cspell-dict-ru_ru",
```

**Comment by nschonni** [comment]
We'll have to see what @Jason3S wants to do 😄

**Comment by Jason3S** [comment]
Thank you for fixing the README.

**Pull request merged**
