### PR TITLE
Update css.txt

### PR DESCRIPTION
**Pull request by sitch**
# Add/Fix Dictionary

Dictionary: _dictionary_

## Description

_description of change_

## References

- _Any source references._

## Checklist

- [ ] By submitting this issue, you agree to follow our
      [Code of Conduct](https://github.com/streetsidesoftware/cspell-dicts/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Jason3S** [comment]
`burgandy`?

image

**Comment by Jason3S** [comment]
@sitch,

Do you have a reference to these colors?

**Comment by sitch** [comment]
Source:

- <https://github.com/vercel/commerce/blob/main/site/lib/colors.ts#L59>
- <https://github.com/vercel/commerce/blob/main/site/lib/colors.ts#L182>

I actually didn't even check the burgundy spelling, just copy and pasted.  But clearly it's misspelled. Fixing now.

**Comment by Jason3S** [comment]
> I think Vercel just made up the name to match the name that Apple uses for their MacBooks, but it's not a real CSS colour

Spacegray is an Apple thing. I'm ok if it gets added to the CSS dict, but it isn't heavily used as far as I can tell from a few Google searches.

**Pull request merged**
