### PR TITLE
chore: Add sample Macedonian text

### PR DESCRIPTION
**Pull request by Jason3S**
# Add/Fix Dictionary

Dictionary: _mk_

## Description

- Add sample text
- Add conditional build step

## Checklist

- [x] By submitting this pull-request, you agree to follow our [Code of Conduct](https://github.com/streetsidesoftware/cspell-dicts/blob/main/CODE_OF_CONDUCT.md)
- [x] Verify that the title starts with the correct prefix:
  - `fix:` - for minor changes like adding words or fixing spelling issues.
  - `feat:` - for a significant change like adding a whole new set of words to a dictionary.
  - `feat!:` - for breaking changes, like file format or licensing changes.
  - `chore:` - for changes that do not impact the content of dictionaries.

### CODE REVIEW

**Comment by Jason3S** [comment]
@Boshkovski-David,

Thank you for creating the dictionary.

Where did you get the source files from? I would like to provide a link to the source and make sure we are using the correct license.

**Comment by Jason3S** [comment]
@Boshkovski-David,

Thank you. Do you have a link to the source? It is necessary for the license.

**Comment by Boshkovski-David** [comment]
Yes, of course. I downloaded the index.dic and index.aff from this repository https://github.com/wooorm/dictionaries/tree/main/dictionaries/mk

**Comment by Jason3S** [comment]
@Boshkovski-David,

Thank you.

**Comment by Jason3S** [comment]
@Boshkovski-David 

> I was wondering. Will these dictionaries be available on the VS Code extension? 

The extension is found here: [Macedonian - Code Spell Checker - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-macedonian)

**Pull request merged**
