### PR TITLE
fix: Add `unfetched`

### PR DESCRIPTION
**Pull request by Nightblade**
to `shared-additional-words.txt`

# Add/Fix Dictionary

Dictionary: `shared-additional-words.txt`

## Description

- add `unfetched`

## References

- [unfetched](https://en.wiktionary.org/wiki/unfetched)

## Checklist

- [x] By submitting this issue, you agree to follow our
      [Code of Conduct](https://github.com/streetsidesoftware/cspell-dicts/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Jason3S** [comment]
@Nightblade,

Thank you for contributing.

This is more likely a Software Term than an English term.

Please check the word frequency here: https://books.google.com/ngrams/graph?content=fetch%2Cunfetch&year_start=2000&year_end=2019&corpus=26&smoothing=0

What does unfetch mean? How do you undo a fetch?

**Comment by Nightblade** [comment]
It's not undoing "a fetch" -- it's something waiting to be fetched.

**Comment by Jason3S** [comment]
@Nightblade,

I misread it as unfetch. You are right, unfetched means not yet fetched.

I took at look on ngram: https://books.google.com/ngrams/graph?content=unfetched%2Cuntriggered&year_start=2000&year_end=2019&corpus=26&smoothing=0

What is the context to add the word? Computer gaming and software should be in those jargon related dictionaries.

I'm just trying to avoid adding too much jargon related words to the English dictionaries.

**Comment by Jason3S** [comment]
@Nightblade,

Thank you for contributing. I am open to adding those words to either [gaming terms](https://github.com/streetsidesoftware/cspell-dicts/tree/main/dictionaries/gaming-terms/src) or [software terms](https://github.com/streetsidesoftware/cspell-dicts/tree/main/dictionaries/software-terms/src).

**Pull request closed without merging**
