### PR TITLE
fix: add terms to GIS dict

### PR DESCRIPTION
**Pull request by jcfranco**
# Add/Fix Dictionary

Dictionary: gis

## Description

Adds more terms to Geographic Information System (GIS) dictionary.

## References

- https://support.esri.com/en-us/gis-dictionary 

## Checklist

- [x] By submitting this pull-request, you agree to follow our [Code of Conduct](https://github.com/streetsidesoftware/cspell-dicts/blob/main/CODE_OF_CONDUCT.md)
- [x] Verify that the title starts with the correct prefix:
  - `fix:` - for minor changes like adding words or fixing spelling issues.
  - `feat:` - for a significant change like adding a whole new set of words to a dictionary.
  - `feat!:` - for breaking changes, like file format or licensing changes.
  - `chore:` - for changes that do not impact the content of dictionaries.

### CODE REVIEW

**Comment by jcfranco** [comment]
@Jason3S I used entries from https://support.esri.com/en-us/gis-dictionary, split space-delimited words and removed duplicates. I'd appreciate your guidance on:

* the correct syntax for entries that should retain spaces (e.g., **NAD 83**, **NAD 1983**, **North American Datum of 1983**) 
* removing common words
* any additional cleanup needed

Thanks!

**Comment by Jason3S** [comment]
@jcfranco,

Thank you.

How is this different from https://github.com/streetsidesoftware/cspell-dicts/tree/main/dictionaries/gis

I think it might be better to have a single GIS package with different dictionaries if it is needed.

**Comment by jcfranco** [comment]
Agreed. I’ve updated the existing dictionary instead.

Thanks again! My upstream was outdated, so it didn’t show up locally, and I missed it in the README as well. 😅

**Comment by jcfranco** [comment]
Sidenote: should `gis`, and possibly others, be added to the specialized dictionary list?

**Comment by Jason3S** [comment]
Thank you.

**Pull request merged**
