### PR TITLE
feat!: Upgrade EO Dict

### PR DESCRIPTION
**Pull request by KieranRobson**
# Add/Fix Dictionary

Dictionary: eo

## Description

Upgrade as part of https://github.com/streetsidesoftware/cspell-dicts/issues/705

When running `yarn test` I get 
```
1/1 .\stdin:Checking: stdin://, File type: *, Language: eo
Dictionary Error with (aws) Error: ENOENT: no such file or directory, open 'C:\Users\kiera\Documents\cspell-dicts\dictionaries\aws\aws.txt.gz'
Dictionary Error with (cryptocurrencies) Error: ENOENT: no such file or directory, open 'C:\Users\kiera\Documents\cspell-dicts\dictionaries\cryptocurrencies\cryptocurrencies.txt.gz'
Dictionary Error with (filetypes) Error: ENOENT: no such file or directory, open 'C:\Users\kiera\Documents\cspell-dicts\dictionaries\filetypes\filetypes.txt.gz'
Dictionary Error with (public-licenses) Error: ENOENT: no such file or directory, open 'C:\Users\kiera\Documents\cspell-dicts\dictionaries\public-licenses\public-licenses.txt.gz'
Checked: stdin://, File type: *, Language: eo ... Issues: 0 2.0552235999999997S
Config file Used: c:\Users\kiera\Documents\cspell-dicts\cspell.json
Dictionaries Used: companies, filetypes, public-licenses, softwareTerms, aws, cryptocurrencies, eo
 2055.22ms
```

## References

NA

## Checklist

- [x] By submitting this issue, you agree to follow our
      [Code of Conduct](https://github.com/streetsidesoftware/cspell-dicts/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by KieranRobson** [comment]
Trying to fix the lint, but get this word as an issue: 

`c:\Users\user\Documents\cspell-dicts-1\dictionaries\eo\eo_license.txt:18:11 - Unknown word (Artur)`

**Comment by KieranRobson** [comment]
I have no idea how to fix the `Artur` issue haha, It doesnt occur with other PRs.

**Comment by Jason3S** [comment]
@KieranRobson,

Thank you. To fix the spelling issue, add `Artur` to `cspell.json`: `words`.

**Comment by Jason3S** [comment]
@KieranRobson,

Thank you.

**Pull request merged**
