### PR TITLE
fix: add  linkcss to npm.txt

### PR DESCRIPTION
**Pull request by digger-yu**
# Add/Fix Dictionary

Dictionary: npm.txt

## Description
add linkcss to npm.txt

## References

LinkCSS: LinkCSS is a responsive and functional CSS framework that uses Web Components and Shadow DOM technology to make it easier for developers to build complex web applications. LinkCSS also originates from an open-source project on GitHub, created and maintained by developer Zhao Wanghu. The project's address is: https://github.com/linkcss/linkcss.

## Checklist

- [x] By submitting this issue, you agree to follow our
      [Code of Conduct](https://github.com/streetsidesoftware/cspell-dicts/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Jason3S** [comment]
@digger-yu,

Do you mean [deck.gl](https://deck.gl/docs/get-started/using-with-react)?

These are package names, not CSS Terms. Please add them to the npm dictionary: https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/npm/src/npm.txt

**Comment by digger-yu** [comment]
@Jason3S  deck.js 

modif done, please check again, If there is a more suitable path, I will change it again

**Comment by digger-yu** [comment]
@Jason3S  done. only add linkcss, please check again

**Comment by Jason3S** [comment]
@digger-yu,

Thank you.

**Pull request merged**
