### PR TITLE
fix: add `TanStack` to companies

### PR DESCRIPTION
**Pull request by rbalet**
# Add/Fix Dictionary

Dictionary: Companies

## Description
Add TanStack to the companies list

## References
- https://tanstack.com/

## Checklist

- [x] By submitting this pull-request, you agree to follow our [Code of Conduct](https://github.com/streetsidesoftware/cspell-dicts/blob/main/CODE_OF_CONDUCT.md)
- [x] Verify that the title starts with the correct prefix:
  - `fix:` - for minor changes like adding words or fixing spelling issues.
  - `feat:` - for a significant change like adding a whole new set of words to a dictionary.
  - `feat!:` - for breaking changes, like file format or licensing changes.
  - `chore:` - for changes that do not impact the content of dictionaries.

### CODE REVIEW

**Comment by rbalet** [comment]
To have a fix on their name while importing their libraries  
image

**Comment by Jason3S** [comment]
@rbalet,

Is TanStack a company? I thought it was just a GitHub organization. I'm reluctant to all GitHub organization to the company. I prefer it to be limited to actual companies.

In any case, `tanstack` is already part of the `npm` dictionary. What version of the spell checker are you using?

**Comment by Jason3S** [comment]
@rbalet,

I have invited you to the `cspell-dict` repository since you have contributed in the past.

Thank you.

**Comment by rbalet** [comment]
Hi @Jason3S, yes, it's more a GitHub organization, sorry, I didn't saw you guys had the `npm` library

I didn't saw that you had a `npm` dictionary, I'll go get it

This is my current version: 3.0.1

image

## Note
I went to the `Pre-release` and it fixed my issue

image

**Pull request closed without merging**
