### PR TITLE
Update it_IT.dic

### PR DESCRIPTION
**Pull request by rbalet**
# Add/Fix Dictionary

Dictionary: it_IT

## Description

Add the `Reindirizzamenti` missing word

## References

- [_Any source references._](https://www.wordsense.eu/reindirizzamenti/)

## Checklist

- [x] By submitting this issue, you agree to follow our
      [Code of Conduct](https://github.com/streetsidesoftware/cspell-dicts/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Jason3S** [comment]
@rbalet,

It looks like Italian hasn't gotten updated to the new layout.

Adding words to `.dic` files will get lost when the Hunspell dictionary is updated.

The other language dictionaries have a `additional_words.txt` file to take care of that issue.

**Comment by rbalet** [comment]
@Jason3S Thx for your quick response

Is it something I can do to migrate this library to the latest way of doing?

**Comment by Jason3S** [comment]
I'll do it now, to work out the steps.

**Comment by Jason3S** [comment]
@rbalet,

Please add words here: https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/it_IT/src/additional_words.txt

It is even possible to add them right from the GitHub website.

**Pull request closed without merging**
